name: Python Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-script-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: python TestMain.py
  ubuntu-specSlice-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          repository: njit-jerse/specSlice
          fetch-depth: 0 # so that spotless can ratchet; see https://github.com/diffplug/spotless/issues/710
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: export SpecSlice PATH
        run: echo "SPECSLICE=$(pwd)" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout specSlice-evaluation repository
        uses: actions/checkout@v3
        with:
         path: specSlice-evaluation
      - name: Run evaluation script
        run: |
          cd specSlice-evaluation
          echo "specSlice path-> $SPECSLICE"
          python main.py
      - name: Check evaluation status
        run: diff -uw src/main/resources/target_status.json specSlice-evaluation/ISSUES/target_status.json
      - name: Compile minimized programs
        run: |
          cd specSlice-evaluation
          sh check_compilation.sh 1
      - name: Check targets compile status
        run: |
          cd specSlice-evaluation
          sh check_compilation.sh 1
          cd ..
          diff -uw src/main/resources/min_program_compile_status.json specSlice-evaluation/ISSUES/compile_status.json
      - name: Check preservation status
        run: diff -uw src/main/resources/preservation_status.json specSlice-evaluation/ISSUES/preservation_status.json
  windows-specSlice-test:
    runs-on: windows-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          repository: njit-jerse/specSlice
          fetch-depth: 0 # so that spotless can ratchet; see https://github.com/diffplug/spotless/issues/710
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout specSlice-evaluation repository
        uses: actions/checkout@v3
        with:
         path: specSlice-evaluation
      - name: Run evaluation script
        # cf-1291: test typical integration test
        # cf-577: download + unzip + rename/file access errors
        # cf-691: download + unzip 2
        # cf-4614: slightly different than expected CF outputs 
        run: |
          set SPECSLICE=%cd%
          cd specSlice-evaluation
          echo specSlice path-^> %SPECSLICE%
          python main.py --debug cf-1291
          python main.py --debug cf-577
          python main.py --debug cf-691
          python main.py --debug cf-4614
          python main.py --debug na-97
        shell: cmd
      - name: Compile minimized programs
        run: |
          set SPECSLICE=%cd%
          cd specSlice-evaluation
          echo specSlice path-^> %SPECSLICE%
          check_compilation.bat 1
        shell: cmd